In [ ]:
import numpy as np

In [ ]:
np

<module 'numpy' from '/home/teo/workspace/machine-learning-zoomcamp-homework/.venv/lib/python3.13/site-packages/numpy/__init__.py'>

In [ ]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
np.full(10, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [ ]:
a = np.array([1,2,3,5,7,12])


In [ ]:
a[2] = 10
a[2]
a

array([ 1,  2, 10,  5,  7, 12])

In [ ]:
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.linspace(0, 1, 11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [ ]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [ ]:
 n= np.array([[1,2,3],[4,5,6]])

In [ ]:
n[1,1] = 20
n[1,1]
n
n[:,1]

array([ 2, 20])

In [ ]:
np.random.seed(2)
np.random.rand(5,2)


array([[68, 46],
       [70, 95],
       [83, 31],
       [66, 80],
       [52, 76]])

In [ ]:
np.random.seed(2)
100 * np.random.rand(5,2)


array([[43.59949021,  2.59262318],
       [54.96624779, 43.53223926],
       [42.03678021, 33.0334821 ],
       [20.4648634 , 61.92709664],
       [29.96546737, 26.68272751]])

In [ ]:
np.random.seed(2)
np.random.randint(low=0, high=100, size=(5,2))

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]])

In [ ]:
np.random.seed(2)
np.random.randn(5,2)

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [ ]:
b = np.arange(5)
# ops on the whole array
c = (b*2 + 10)**2 / 100
c


array([1.  , 1.44, 1.96, 2.56, 3.24])

In [ ]:
b + c

array([1.  , 2.44, 3.96, 5.56, 7.24])

In [ ]:
b>=2

array([False, False,  True,  True,  True])

In [ ]:
b > c

array([False, False,  True,  True,  True])

In [ ]:
# filter elements that satisfy a condition
b[b > c]

array([2, 3, 4])

In [ ]:
#summarizing operations
b.min()

np.int64(0)

In [ ]:
b.std()

np.float64(1.4142135623730951)

In [ ]:
b.sum()

np.int64(10)

In [ ]:
b.mean()

np.float64(2.0)

# Vector operations

u * v in numpy is an element-wise product, not a dot product (vTu)

In [ ]:
u = np.array([2, 4, 5, 6])
v = np.array([1, 0, 0, 2])

In [ ]:
u * v

array([ 2,  0,  0, 12])

In [ ]:
#def dot(u, v):
#    assert u.shape[0] == v.shape[0]
#    return sum(u[i] * v[i] for i in range(len(u)))

# it already exists in numpy
u.dot(v)

np.int64(14)

In [ ]:
# matrix vector product Uv
U = np.array([[2, 4, 5, 6],
              [1, 2, 1, 2],
              [3, 1, 2, 1]])

U.dot(v)

array([14,  5,  5])

In [ ]:
# matrix matrix product UV
V= np.array([[1, 1, 2],
             [0, 0.5, 1],
             [0, 2, 1],
             [2, 1, 0]])
U.dot(V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

In [ ]:
U @ V

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

In [ ]:
# identity matrix
I = np.eye(4)
I

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
U.dot(I)

array([[2., 4., 5., 6.],
       [1., 2., 1., 2.],
       [3., 1., 2., 1.]])

In [ ]:
# inverse
Vs = V[[0, 1, 2]]
Vs

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ]])

In [ ]:
Vs_inv = np.linalg.inv(Vs)
Vs_inv

array([[ 1.        , -2.        ,  0.        ],
       [ 0.        , -0.66666667,  0.66666667],
       [ 0.        ,  1.33333333, -0.33333333]])

In [ ]:
Vs_inv.dot(Vs)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
Vs.dot(Vs_inv)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])